/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AppIndexRouteImport } from './routes/_app.index'
import { Route as AppWishesRouteImport } from './routes/_app.wishes'
import { Route as AppSectionsRouteImport } from './routes/_app.sections'
import { Route as AppPartnerRouteImport } from './routes/_app.partner'
import { Route as AppLibraryRouteImport } from './routes/_app.library'
import { Route as AppFoursomeRouteImport } from './routes/_app.foursome'
import { Route as AppCommunityRouteImport } from './routes/_app.community'
import { Route as AppBuddyRouteImport } from './routes/_app.buddy'

const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppWishesRoute = AppWishesRouteImport.update({
  id: '/wishes',
  path: '/wishes',
  getParentRoute: () => AppRoute,
} as any)
const AppSectionsRoute = AppSectionsRouteImport.update({
  id: '/sections',
  path: '/sections',
  getParentRoute: () => AppRoute,
} as any)
const AppPartnerRoute = AppPartnerRouteImport.update({
  id: '/partner',
  path: '/partner',
  getParentRoute: () => AppRoute,
} as any)
const AppLibraryRoute = AppLibraryRouteImport.update({
  id: '/library',
  path: '/library',
  getParentRoute: () => AppRoute,
} as any)
const AppFoursomeRoute = AppFoursomeRouteImport.update({
  id: '/foursome',
  path: '/foursome',
  getParentRoute: () => AppRoute,
} as any)
const AppCommunityRoute = AppCommunityRouteImport.update({
  id: '/community',
  path: '/community',
  getParentRoute: () => AppRoute,
} as any)
const AppBuddyRoute = AppBuddyRouteImport.update({
  id: '/buddy',
  path: '/buddy',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/onboarding': typeof OnboardingRoute
  '/buddy': typeof AppBuddyRoute
  '/community': typeof AppCommunityRoute
  '/foursome': typeof AppFoursomeRoute
  '/library': typeof AppLibraryRoute
  '/partner': typeof AppPartnerRoute
  '/sections': typeof AppSectionsRoute
  '/wishes': typeof AppWishesRoute
}
export interface FileRoutesByTo {
  '/onboarding': typeof OnboardingRoute
  '/buddy': typeof AppBuddyRoute
  '/community': typeof AppCommunityRoute
  '/foursome': typeof AppFoursomeRoute
  '/library': typeof AppLibraryRoute
  '/partner': typeof AppPartnerRoute
  '/sections': typeof AppSectionsRoute
  '/wishes': typeof AppWishesRoute
  '/': typeof AppIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/onboarding': typeof OnboardingRoute
  '/_app/buddy': typeof AppBuddyRoute
  '/_app/community': typeof AppCommunityRoute
  '/_app/foursome': typeof AppFoursomeRoute
  '/_app/library': typeof AppLibraryRoute
  '/_app/partner': typeof AppPartnerRoute
  '/_app/sections': typeof AppSectionsRoute
  '/_app/wishes': typeof AppWishesRoute
  '/_app/': typeof AppIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/onboarding'
    | '/buddy'
    | '/community'
    | '/foursome'
    | '/library'
    | '/partner'
    | '/sections'
    | '/wishes'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/onboarding'
    | '/buddy'
    | '/community'
    | '/foursome'
    | '/library'
    | '/partner'
    | '/sections'
    | '/wishes'
    | '/'
  id:
    | '__root__'
    | '/_app'
    | '/onboarding'
    | '/_app/buddy'
    | '/_app/community'
    | '/_app/foursome'
    | '/_app/library'
    | '/_app/partner'
    | '/_app/sections'
    | '/_app/wishes'
    | '/_app/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  OnboardingRoute: typeof OnboardingRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/wishes': {
      id: '/_app/wishes'
      path: '/wishes'
      fullPath: '/wishes'
      preLoaderRoute: typeof AppWishesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/sections': {
      id: '/_app/sections'
      path: '/sections'
      fullPath: '/sections'
      preLoaderRoute: typeof AppSectionsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/partner': {
      id: '/_app/partner'
      path: '/partner'
      fullPath: '/partner'
      preLoaderRoute: typeof AppPartnerRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/library': {
      id: '/_app/library'
      path: '/library'
      fullPath: '/library'
      preLoaderRoute: typeof AppLibraryRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/foursome': {
      id: '/_app/foursome'
      path: '/foursome'
      fullPath: '/foursome'
      preLoaderRoute: typeof AppFoursomeRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/community': {
      id: '/_app/community'
      path: '/community'
      fullPath: '/community'
      preLoaderRoute: typeof AppCommunityRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/buddy': {
      id: '/_app/buddy'
      path: '/buddy'
      fullPath: '/buddy'
      preLoaderRoute: typeof AppBuddyRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppBuddyRoute: typeof AppBuddyRoute
  AppCommunityRoute: typeof AppCommunityRoute
  AppFoursomeRoute: typeof AppFoursomeRoute
  AppLibraryRoute: typeof AppLibraryRoute
  AppPartnerRoute: typeof AppPartnerRoute
  AppSectionsRoute: typeof AppSectionsRoute
  AppWishesRoute: typeof AppWishesRoute
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppBuddyRoute: AppBuddyRoute,
  AppCommunityRoute: AppCommunityRoute,
  AppFoursomeRoute: AppFoursomeRoute,
  AppLibraryRoute: AppLibraryRoute,
  AppPartnerRoute: AppPartnerRoute,
  AppSectionsRoute: AppSectionsRoute,
  AppWishesRoute: AppWishesRoute,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  OnboardingRoute: OnboardingRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
