/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AppIndexRouteImport } from './routes/_app.index'
import { Route as AppWishesRouteImport } from './routes/_app.wishes'
import { Route as AppValuesRouteImport } from './routes/_app.values'
import { Route as AppSectionsRouteImport } from './routes/_app.sections'
import { Route as AppQualitiesRouteImport } from './routes/_app.qualities'
import { Route as AppPartnerRouteImport } from './routes/_app.partner'
import { Route as AppNeedsRouteImport } from './routes/_app.needs'
import { Route as AppLibraryRouteImport } from './routes/_app.library'
import { Route as AppHabitsRouteImport } from './routes/_app.habits'
import { Route as AppFoursomeRouteImport } from './routes/_app.foursome'
import { Route as AppCommunityRouteImport } from './routes/_app.community'
import { Route as AppBuddyRouteImport } from './routes/_app.buddy'
import { Route as AppPracticeWishesChargeRouteImport } from './routes/_app.practice.wishes-charge'
import { Route as AppPracticeWishesRouteImport } from './routes/_app.practice.wishes'
import { Route as AppPracticeStepRouteImport } from './routes/_app.practice.step'
import { Route as AppPracticeSkillRouteImport } from './routes/_app.practice.skill'
import { Route as AppPracticeSelfProgRouteImport } from './routes/_app.practice.self-prog'
import { Route as AppPracticeEssayRouteImport } from './routes/_app.practice.essay'

const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppWishesRoute = AppWishesRouteImport.update({
  id: '/wishes',
  path: '/wishes',
  getParentRoute: () => AppRoute,
} as any)
const AppValuesRoute = AppValuesRouteImport.update({
  id: '/values',
  path: '/values',
  getParentRoute: () => AppRoute,
} as any)
const AppSectionsRoute = AppSectionsRouteImport.update({
  id: '/sections',
  path: '/sections',
  getParentRoute: () => AppRoute,
} as any)
const AppQualitiesRoute = AppQualitiesRouteImport.update({
  id: '/qualities',
  path: '/qualities',
  getParentRoute: () => AppRoute,
} as any)
const AppPartnerRoute = AppPartnerRouteImport.update({
  id: '/partner',
  path: '/partner',
  getParentRoute: () => AppRoute,
} as any)
const AppNeedsRoute = AppNeedsRouteImport.update({
  id: '/needs',
  path: '/needs',
  getParentRoute: () => AppRoute,
} as any)
const AppLibraryRoute = AppLibraryRouteImport.update({
  id: '/library',
  path: '/library',
  getParentRoute: () => AppRoute,
} as any)
const AppHabitsRoute = AppHabitsRouteImport.update({
  id: '/habits',
  path: '/habits',
  getParentRoute: () => AppRoute,
} as any)
const AppFoursomeRoute = AppFoursomeRouteImport.update({
  id: '/foursome',
  path: '/foursome',
  getParentRoute: () => AppRoute,
} as any)
const AppCommunityRoute = AppCommunityRouteImport.update({
  id: '/community',
  path: '/community',
  getParentRoute: () => AppRoute,
} as any)
const AppBuddyRoute = AppBuddyRouteImport.update({
  id: '/buddy',
  path: '/buddy',
  getParentRoute: () => AppRoute,
} as any)
const AppPracticeWishesChargeRoute = AppPracticeWishesChargeRouteImport.update({
  id: '/practice/wishes-charge',
  path: '/practice/wishes-charge',
  getParentRoute: () => AppRoute,
} as any)
const AppPracticeWishesRoute = AppPracticeWishesRouteImport.update({
  id: '/practice/wishes',
  path: '/practice/wishes',
  getParentRoute: () => AppRoute,
} as any)
const AppPracticeStepRoute = AppPracticeStepRouteImport.update({
  id: '/practice/step',
  path: '/practice/step',
  getParentRoute: () => AppRoute,
} as any)
const AppPracticeSkillRoute = AppPracticeSkillRouteImport.update({
  id: '/practice/skill',
  path: '/practice/skill',
  getParentRoute: () => AppRoute,
} as any)
const AppPracticeSelfProgRoute = AppPracticeSelfProgRouteImport.update({
  id: '/practice/self-prog',
  path: '/practice/self-prog',
  getParentRoute: () => AppRoute,
} as any)
const AppPracticeEssayRoute = AppPracticeEssayRouteImport.update({
  id: '/practice/essay',
  path: '/practice/essay',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/onboarding': typeof OnboardingRoute
  '/buddy': typeof AppBuddyRoute
  '/community': typeof AppCommunityRoute
  '/foursome': typeof AppFoursomeRoute
  '/habits': typeof AppHabitsRoute
  '/library': typeof AppLibraryRoute
  '/needs': typeof AppNeedsRoute
  '/partner': typeof AppPartnerRoute
  '/qualities': typeof AppQualitiesRoute
  '/sections': typeof AppSectionsRoute
  '/values': typeof AppValuesRoute
  '/wishes': typeof AppWishesRoute
  '/practice/essay': typeof AppPracticeEssayRoute
  '/practice/self-prog': typeof AppPracticeSelfProgRoute
  '/practice/skill': typeof AppPracticeSkillRoute
  '/practice/step': typeof AppPracticeStepRoute
  '/practice/wishes': typeof AppPracticeWishesRoute
  '/practice/wishes-charge': typeof AppPracticeWishesChargeRoute
}
export interface FileRoutesByTo {
  '/onboarding': typeof OnboardingRoute
  '/buddy': typeof AppBuddyRoute
  '/community': typeof AppCommunityRoute
  '/foursome': typeof AppFoursomeRoute
  '/habits': typeof AppHabitsRoute
  '/library': typeof AppLibraryRoute
  '/needs': typeof AppNeedsRoute
  '/partner': typeof AppPartnerRoute
  '/qualities': typeof AppQualitiesRoute
  '/sections': typeof AppSectionsRoute
  '/values': typeof AppValuesRoute
  '/wishes': typeof AppWishesRoute
  '/': typeof AppIndexRoute
  '/practice/essay': typeof AppPracticeEssayRoute
  '/practice/self-prog': typeof AppPracticeSelfProgRoute
  '/practice/skill': typeof AppPracticeSkillRoute
  '/practice/step': typeof AppPracticeStepRoute
  '/practice/wishes': typeof AppPracticeWishesRoute
  '/practice/wishes-charge': typeof AppPracticeWishesChargeRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/onboarding': typeof OnboardingRoute
  '/_app/buddy': typeof AppBuddyRoute
  '/_app/community': typeof AppCommunityRoute
  '/_app/foursome': typeof AppFoursomeRoute
  '/_app/habits': typeof AppHabitsRoute
  '/_app/library': typeof AppLibraryRoute
  '/_app/needs': typeof AppNeedsRoute
  '/_app/partner': typeof AppPartnerRoute
  '/_app/qualities': typeof AppQualitiesRoute
  '/_app/sections': typeof AppSectionsRoute
  '/_app/values': typeof AppValuesRoute
  '/_app/wishes': typeof AppWishesRoute
  '/_app/': typeof AppIndexRoute
  '/_app/practice/essay': typeof AppPracticeEssayRoute
  '/_app/practice/self-prog': typeof AppPracticeSelfProgRoute
  '/_app/practice/skill': typeof AppPracticeSkillRoute
  '/_app/practice/step': typeof AppPracticeStepRoute
  '/_app/practice/wishes': typeof AppPracticeWishesRoute
  '/_app/practice/wishes-charge': typeof AppPracticeWishesChargeRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/onboarding'
    | '/buddy'
    | '/community'
    | '/foursome'
    | '/habits'
    | '/library'
    | '/needs'
    | '/partner'
    | '/qualities'
    | '/sections'
    | '/values'
    | '/wishes'
    | '/practice/essay'
    | '/practice/self-prog'
    | '/practice/skill'
    | '/practice/step'
    | '/practice/wishes'
    | '/practice/wishes-charge'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/onboarding'
    | '/buddy'
    | '/community'
    | '/foursome'
    | '/habits'
    | '/library'
    | '/needs'
    | '/partner'
    | '/qualities'
    | '/sections'
    | '/values'
    | '/wishes'
    | '/'
    | '/practice/essay'
    | '/practice/self-prog'
    | '/practice/skill'
    | '/practice/step'
    | '/practice/wishes'
    | '/practice/wishes-charge'
  id:
    | '__root__'
    | '/_app'
    | '/onboarding'
    | '/_app/buddy'
    | '/_app/community'
    | '/_app/foursome'
    | '/_app/habits'
    | '/_app/library'
    | '/_app/needs'
    | '/_app/partner'
    | '/_app/qualities'
    | '/_app/sections'
    | '/_app/values'
    | '/_app/wishes'
    | '/_app/'
    | '/_app/practice/essay'
    | '/_app/practice/self-prog'
    | '/_app/practice/skill'
    | '/_app/practice/step'
    | '/_app/practice/wishes'
    | '/_app/practice/wishes-charge'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  OnboardingRoute: typeof OnboardingRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/wishes': {
      id: '/_app/wishes'
      path: '/wishes'
      fullPath: '/wishes'
      preLoaderRoute: typeof AppWishesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/values': {
      id: '/_app/values'
      path: '/values'
      fullPath: '/values'
      preLoaderRoute: typeof AppValuesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/sections': {
      id: '/_app/sections'
      path: '/sections'
      fullPath: '/sections'
      preLoaderRoute: typeof AppSectionsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/qualities': {
      id: '/_app/qualities'
      path: '/qualities'
      fullPath: '/qualities'
      preLoaderRoute: typeof AppQualitiesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/partner': {
      id: '/_app/partner'
      path: '/partner'
      fullPath: '/partner'
      preLoaderRoute: typeof AppPartnerRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/needs': {
      id: '/_app/needs'
      path: '/needs'
      fullPath: '/needs'
      preLoaderRoute: typeof AppNeedsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/library': {
      id: '/_app/library'
      path: '/library'
      fullPath: '/library'
      preLoaderRoute: typeof AppLibraryRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/habits': {
      id: '/_app/habits'
      path: '/habits'
      fullPath: '/habits'
      preLoaderRoute: typeof AppHabitsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/foursome': {
      id: '/_app/foursome'
      path: '/foursome'
      fullPath: '/foursome'
      preLoaderRoute: typeof AppFoursomeRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/community': {
      id: '/_app/community'
      path: '/community'
      fullPath: '/community'
      preLoaderRoute: typeof AppCommunityRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/buddy': {
      id: '/_app/buddy'
      path: '/buddy'
      fullPath: '/buddy'
      preLoaderRoute: typeof AppBuddyRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/practice/wishes-charge': {
      id: '/_app/practice/wishes-charge'
      path: '/practice/wishes-charge'
      fullPath: '/practice/wishes-charge'
      preLoaderRoute: typeof AppPracticeWishesChargeRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/practice/wishes': {
      id: '/_app/practice/wishes'
      path: '/practice/wishes'
      fullPath: '/practice/wishes'
      preLoaderRoute: typeof AppPracticeWishesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/practice/step': {
      id: '/_app/practice/step'
      path: '/practice/step'
      fullPath: '/practice/step'
      preLoaderRoute: typeof AppPracticeStepRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/practice/skill': {
      id: '/_app/practice/skill'
      path: '/practice/skill'
      fullPath: '/practice/skill'
      preLoaderRoute: typeof AppPracticeSkillRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/practice/self-prog': {
      id: '/_app/practice/self-prog'
      path: '/practice/self-prog'
      fullPath: '/practice/self-prog'
      preLoaderRoute: typeof AppPracticeSelfProgRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/practice/essay': {
      id: '/_app/practice/essay'
      path: '/practice/essay'
      fullPath: '/practice/essay'
      preLoaderRoute: typeof AppPracticeEssayRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppBuddyRoute: typeof AppBuddyRoute
  AppCommunityRoute: typeof AppCommunityRoute
  AppFoursomeRoute: typeof AppFoursomeRoute
  AppHabitsRoute: typeof AppHabitsRoute
  AppLibraryRoute: typeof AppLibraryRoute
  AppNeedsRoute: typeof AppNeedsRoute
  AppPartnerRoute: typeof AppPartnerRoute
  AppQualitiesRoute: typeof AppQualitiesRoute
  AppSectionsRoute: typeof AppSectionsRoute
  AppValuesRoute: typeof AppValuesRoute
  AppWishesRoute: typeof AppWishesRoute
  AppIndexRoute: typeof AppIndexRoute
  AppPracticeEssayRoute: typeof AppPracticeEssayRoute
  AppPracticeSelfProgRoute: typeof AppPracticeSelfProgRoute
  AppPracticeSkillRoute: typeof AppPracticeSkillRoute
  AppPracticeStepRoute: typeof AppPracticeStepRoute
  AppPracticeWishesRoute: typeof AppPracticeWishesRoute
  AppPracticeWishesChargeRoute: typeof AppPracticeWishesChargeRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppBuddyRoute: AppBuddyRoute,
  AppCommunityRoute: AppCommunityRoute,
  AppFoursomeRoute: AppFoursomeRoute,
  AppHabitsRoute: AppHabitsRoute,
  AppLibraryRoute: AppLibraryRoute,
  AppNeedsRoute: AppNeedsRoute,
  AppPartnerRoute: AppPartnerRoute,
  AppQualitiesRoute: AppQualitiesRoute,
  AppSectionsRoute: AppSectionsRoute,
  AppValuesRoute: AppValuesRoute,
  AppWishesRoute: AppWishesRoute,
  AppIndexRoute: AppIndexRoute,
  AppPracticeEssayRoute: AppPracticeEssayRoute,
  AppPracticeSelfProgRoute: AppPracticeSelfProgRoute,
  AppPracticeSkillRoute: AppPracticeSkillRoute,
  AppPracticeStepRoute: AppPracticeStepRoute,
  AppPracticeWishesRoute: AppPracticeWishesRoute,
  AppPracticeWishesChargeRoute: AppPracticeWishesChargeRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  OnboardingRoute: OnboardingRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
